Minor updates
Updates to login.html
Removed Login Code from queries.js and put in app.js
Running into bug with the login code
- "TypeError: db.all is not a function" at   app.js:65:8